In [12]:
import re
import pandas as pd
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

In [13]:
df=pd.read_csv(r'C:\Users\YASHVIR\OneDrive\Attachments\PROJECTS\NLP\imdb\dataset\IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [14]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [15]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [16]:
df.duplicated().sum()

np.int64(418)

In [17]:
df = df.drop_duplicates().reset_index(drop=True)
df.shape

(49582, 2)

In [18]:
df[:2]

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive

In [19]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [20]:
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('wordnet')
nltk.download('punkt_tab')

[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\YASHVIR\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\YASHVIR\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\YASHVIR\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [21]:
def preprocess(text):
    text = re.sub(r"<br\s*/?>", " ", text)      # do this first
    text = re.sub(r'[^a-zA-Z\s]', '', text)     # then this
    text = re.sub(r'\s+', ' ', text).strip()
    text = text.lower()
    tokens = word_tokenize(text)
    cleaned_tokens = [lemmatizer.lemmatize(t, pos='v') for t in tokens if t not in stop_words]
    return ' '.join(cleaned_tokens)

In [22]:
df['clean_review'] = df['review'].apply(preprocess)
df['label'] = df['sentiment'].map({'positive': 1, 'negative': 0})

df.to_csv('cleaned_data.csv', index=False)
print(f"Saved {len(df)} cleaned rows to cleaned_data.csv")

Saved 49582 cleaned rows to cleaned_data.csv